build/versioning: temporary disable parts that we don't support
storj/gateway-mint pull request #9
Opened 2023-11-10 10:19 UTC by mniewrzal

2023-11-10 11:09 UTC, amwolff requested changes, later dismissed
Can you add something like `TODO: uncomment once supported by Storj` to every comment block here? Just so that we don't forget we have these disabled.

2023-11-13 08:40 UTC, mniewrzal commented
> Can you add something like `TODO: uncomment once supported by Storj` to every comment block here? Just so that we don't forget we have these disabled.

Done.

2023-11-13 16:34 UTC, halkyon approved these changes

2023-11-14 14:18 UTC, jtolio approved these changes

2023-11-14 15:54 UTC, merged